#!/usr/bin/env python3
"""Generate README.md (the GitHub profile page) from data/profile.json.

The README is a stack of theme-aware SVG cards (assets/cards/*.svg) plus a
collapsible plain-text version for screen readers, search engines and copy/paste.
"""
from __future__ import annotations

from html import escape as e
from pathlib import Path

from lib import content as C
from lib import markdown

ROOT = Path(__file__).resolve().parents[1]
CARD_DIR = "assets/cards"
WIDTH = 830


def picture(name: str, alt: str, width: int | None = None) -> str:
    w = f' width="{width}"' if width else ""
    return (
        f'<picture>\n'
        f'  <source media="(prefers-color-scheme: dark)" srcset="{CARD_DIR}/{name}-dark.svg">\n'
        f'  <img src="{CARD_DIR}/{name}-light.svg" alt="{e(alt, quote=True)}"{w}>\n'
        f'</picture>'
    )


def card(name: str, alt: str, href: str | None = None) -> str:
    pic = picture(name, alt, WIDTH)
    if href:
        pic = f'<a href="{e(href, quote=True)}">\n{pic}\n</a>'
    return f"<p align=\"center\">\n{pic}\n</p>\n"


def render(p: dict, contrib: dict) -> str:
    base = p["site"]["url"].rstrip("/") + "/"
    user = p["person"]["username"]
    per = p["person"]

    out: list[str] = []
    out.append("<!-- Generated by scripts/build.py from data/profile.json. Edit the JSON, not this file. -->\n")
    out.append(card("hero", f"{per['name']}, {per['role']}. " + "; ".join(C.parts_text(r["parts"]) for r in p["overview"]) + ".", base))

    # social buttons: separate images so each one is a real link
    btns = []
    for l in p["links"]:
        btns.append(f'<a href="{e(l["href"], quote=True)}">\n{picture("social-" + l["id"], l["label"] + " — " + l["handle"])}\n</a>')
    btns.append(f'<a href="{e(base, quote=True)}">\n{picture("social-site", "Interactive version of this profile")}\n</a>')
    out.append('<p align="center">\n' + "\n".join(btns) + "\n</p>\n")

    if p.get("cta"):
        out.append(f'<p align="center"><sub>{e(p["cta"])}</sub></p>\n')

    r = contrib.get("range", {})
    contrib_alt = f"GitHub contribution heatmap: {contrib.get('total_contributions', 0)} contributions"
    if r.get("start"):
        contrib_alt += f", {C.fmt_day(r['start'])} – {C.fmt_day(r['end'])}"
    out.append(card("contributions", contrib_alt, f"https://github.com/{user}"))

    out.append(card("about", "About: " + " ".join(C.plain(x) for x in p["about"]), base + "#about"))
    out.append(card("principles", "Principles: " + "; ".join(f"{x['verb']} — {x['title']}" for x in p["principles"]), base + "#principles"))
    out.append(card("focus", "Focus areas: " + "; ".join(x["title"] for x in p["focus"]), base + "#focus"))
    out.append(card("stack", "Stack: " + "; ".join(f"{g['name']} ({', '.join(x['name'] for x in g['items'])})" for g in p["stack"]), base + "#stack"))
    out.append(card("experience", "Experience: " + "; ".join(f"{x['company']} — " + ", ".join(pp['title'] for pp in x['positions']) for x in p["experience"]), base + "#experience"))
    out.append(card("education", "Education: " + "; ".join(f"{x['degree']}, {x['field']} — {x['school']}" for x in p["education"]), base + "#education"))
    out.append(card("projects", "Projects: " + "; ".join(f"{x['name']} ({x['kind']})" for x in p["projects"]), base + "#projects"))

    # public repos as real links under the cards (an image can't hold several links)
    public = [x for x in p["projects"] if x.get("url")]
    if public:
        out.append('<p align="center"><sub>Open source: ' + " · ".join(f'<a href="{e(x["url"], quote=True)}">{e(x["name"])}</a>' for x in public) + "</sub></p>\n")

    out.append(card("lab", "Lab: " + "; ".join(x["name"] for x in p["lab"]["items"]), base + "#lab"))
    out.append('<p align="center"><sub>Lab specs: ' + " · ".join(f'<a href="{e(x["url"], quote=True)}">{e(x["name"])}</a>' for x in p["lab"]["items"]) + "</sub></p>\n")
    out.append(card("research", "Research signals: " + "; ".join(p["research"]), base + "#research"))
    out.append(card("footer", "Build details and credits", f"https://github.com/{p['site']['repo']}"))

    out.append("<details>\n<summary>Plain-text version (screen readers, search, copy &amp; paste)</summary>\n\n")
    out.append(markdown.render(p, contrib, base))
    out.append("\n</details>\n")
    return "\n".join(out)


def build() -> None:
    p = C.load_profile()
    text = render(p, C.load_contributions())
    (ROOT / "README.md").write_text(text, encoding="utf-8")
    print(f"readme: wrote README.md ({len(text) // 1024} KB)")


if __name__ == "__main__":
    build()
